### ISSUE TITLE
Bad Readme file

### ISSUE THREAD

**Issue by barceyken** [Azure-Samples/media-services-javascript-azure-media-player-social-share-plugin#1]
The Readme file is from the Zoom plugin.

By other hand the Demo link on [Azure plugins page](https://amp.azure.net/libs/amp/latest/docs/PLUGINS.html) has a bad link, it should be [Share demo](http://sr-test.azurewebsites.net/Tests/Plugin%20Gallery/plugins/zoom/example.html).

:)

**Comment by sraje** [comment]
Thanks for bringing this to our attention. The README/Plugin page have both been updated. Happy coding :)
